channels:
  - conda-forge
  - https://repo.continuum.io/pkgs/free
  - defaults
dependencies:
  - python=3.7
  - compilers
  - cmake
  - pybind11[version='>=2.10.0']
  - pip:
    - sphinx
    - sphinx_rtd_theme
    - autodocsumm
    - sphinx-autodoc-typehints
    - versioneer
    - pytest==6.2.4
    - sphinx_rtd_theme==1.0.0

